
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/blogproj/staticfiles
    environment:
      - DATABASE_URL=sqlite:////blogproj/db.sqlite3

volumes:
  staticfiles: