apiVersion: v1
kind: Deployment
metadata:
  name: sqlite-pod
  labels:
    app: sqlite
spec:
  containers:
    - name: sqlite-container
      image: alpine
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: "/data"
          name: sqlite-storage
  volumes:
    - name: sqlite-storage
      persistentVolumeClaim:
        claimName: sqlite-pvc
